// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmmJfPYOCA6U6gYQGIoClSjavL34Iiyr0',
    appId: '1:180565796746:web:430ee24f2a736edd664a73',
    messagingSenderId: '180565796746',
    projectId: 'vertigo-3faec',
    authDomain: 'vertigo-3faec.firebaseapp.com',
    storageBucket: 'vertigo-3faec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIUV0BCAxNDjvu7CHUeEPzcyscoNkb-eM',
    appId: '1:180565796746:android:44def319a0f10e65664a73',
    messagingSenderId: '180565796746',
    projectId: 'vertigo-3faec',
    storageBucket: 'vertigo-3faec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi6FfkMZrtyfkhSqoxmMopR_5R7Tupglw',
    appId: '1:180565796746:ios:0e60151d8a4219bd664a73',
    messagingSenderId: '180565796746',
    projectId: 'vertigo-3faec',
    storageBucket: 'vertigo-3faec.firebasestorage.app',
    iosBundleId: 'com.example.socialNetworkFlutter',
  );
}
